language: scala
install:
  - pip install --user codecov

scala:
- 2.10.7
- 2.11.12
- 2.12.6
- 2.13.0-M4

jdk:
- oraclejdk8

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

script:
  - travis_wait 60 scripts/travis-publish.sh

env:
  global:
  - secure: eXcMQIb0hHeaJsJGaJYhLS8aONu5YnhK1NOHJZGTBIb6ukSd48uXm6xNgBMozgkOEUBXyrBU9ZnCOxSS+HmJZDbK0Wkr90C4sZH7dHBZYMN3hNfCp5SjPFY2+TgrYZ24G8s/BPei6725AlbXM0vmdXPsvxaOvT36d2Ej7xto8+c=
  - secure: c3IO3G34aTFD+fh/5vqc3sCgwMaClPDziYQDCEUqQBOQFdTS7wbBZFVpqTUUlkMLkeyHZ0BGSLUiDZnu8TGGITtgJBaCUchhLYK5WOavyzCl/NPVOBebviazgtBOzPDKyYDcahjmxCGrMspTiRei86VgCdkNIvldJJm7zK1OAOU=

sudo: false

notifications:
  irc: "chat.freenode.net#shapeless"
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/e58e987de2f64f32c8c6

matrix:
  include:
  - scala: 2.11.12
    env: NATIVE=true
    jdk: oraclejdk8
    sudo: required
    before_install:
    - curl https://raw.githubusercontent.com/scala-native/scala-native/master/scripts/travis_setup.sh | bash -x
