os: linux
dist: trusty
language: scala

jdk:
  - oraclejdk8

scala:
  - 2.11.12
  - 2.12.11
  - 2.13.2

env:
  - {}
  - SCALA_JS_VERSION=0.6.32
  - SCALA_JS_VERSION=1.0.1

stages:
  - name: test
  - name: release
    if: ((branch = master AND type = push) OR (tag IS present)) AND NOT fork

cache:
  directories:
    - $HOME/.cache/coursier
    - $HOME/.ivy2/cache
    - $HOME/.sbt

script: sbt ++$TRAVIS_SCALA_VERSION clean validateCI

notifications:
  irc: "chat.freenode.net#shapeless"
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/e58e987de2f64f32c8c6

jobs:
  include:
    - stage: test
      env:
        - SCALA_NATIVE=true
      before_install:
        - curl https://raw.githubusercontent.com/scala-native/scala-native/master/scripts/travis_setup.sh | bash -x
    - stage: release
      before_install:
        - git fetch --tags
        - curl https://raw.githubusercontent.com/scala-native/scala-native/master/scripts/travis_setup.sh | bash -x
      script:
        - sbt ci-release
        - SCALA_JS_VERSION=0.6.32 sbt clean sonatypeBundleClean ci-release
