os: linux
dist: bionic
language: scala

jdk:
  - openjdk8

scala:
  - 2.11.12
  - 2.12.13
  - 2.13.4

env:
  - {}
  - SCALA_JS_VERSION=0.6.33
  - SCALA_JS_VERSION=1.4.0

stages:
  - name: test
  - name: release
    if: ((branch = master AND type = push) OR (tag IS present)) AND NOT fork

cache:
  directories:
    - $HOME/.cache/coursier
    - $HOME/.ivy2/cache
    - $HOME/.sbt

script: sbt ++$TRAVIS_SCALA_VERSION! clean validateCI

notifications:
  irc: "chat.freenode.net#shapeless"
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/e58e987de2f64f32c8c6

jobs:
  include:
    - stage: test
      env:
        - SCALA_NATIVE=true
    - stage: release
      before_install:
        - git fetch --tags
      script:
        - sbt ci-release
        - SCALA_JS_VERSION=0.6.33 sbt clean sonatypeBundleClean ci-release
