language: scala
scala:
- 2.10.4
jdk:
- oraclejdk7
- openjdk6
script: sbt ++${TRAVIS_SCALA_VERSION} test $(if [[ "${TRAVIS_PULL_REQUEST}" == "false" && ${JAVA_HOME} == $(jdk_switcher home oraclejdk7) && ("${TRAVIS_BRANCH}" == "master" || "${TRAVIS_BRANCH}" == "scala-2.11.x")]]; then echo "publish";  fi)
env:
  global:
  - secure: "Yi/MWSvXrePnkVbiGxh9ZaRnh4EAayheY9fE8kHz+WOFYDA2cdBER60KDLZFC8T3U0lvpx1e7rbCyGu46Z9ypqQ50VgDMk+49N3NYvP2RAfnqecSyaDEzq5r093Hby+jEQUPApmTun8/pPiJTEO5sHCb+aiAGIA4zg8+ealZa2g="
  - secure: "PMudLwIAqd13AQe7lkNW6wj8CkFvZFYRMgU7emHosmSL198PDH71+nLAhQD93PA1K8fXTPJRvX7C6s8NGi/rinmcFLABXv0NjuPdrYBsbwAWaTQlmc/b+HS3dIPVbmbjyG8az6bZdYbXjaRQZu6vvmIdgJizEGqxvK96yRqNPRw="
