language: scala

scala:
- 2.11.7
- 2.12.0-M1

jdk:
- oraclejdk7
- openjdk6

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

script:
  - if [[ "${TRAVIS_PULL_REQUEST}" == "false" &&
         ${JAVA_HOME} == $(jdk_switcher home oraclejdk7) &&
         ("${TRAVIS_BRANCH}" == "master" || "${TRAVIS_BRANCH}" == "scala-2.10.x" ||
          "${TRAVIS_BRANCH}" == "scalajs-2.11.x" || "${TRAVIS_BRANCH}" == "scalajs-2.10.x") &&
         $(cat version.sbt) =~ "-SNAPSHOT"
    ]]; then
      sbt ++${TRAVIS_SCALA_VERSION} test mima-report-binary-issues publish ;
    else
      sbt ++${TRAVIS_SCALA_VERSION} test mima-report-binary-issues ;
    fi

env:
  global:
  - secure: Tk9OHnvqs1BGHWZSE2kWUeCJntDWG6kkpmD+5pcWJdBa+IDmT1cLMgOd3GGaT8V/x2qV39v9hYvVwLYLiQPSDVKRmZmH2l5kZMBTVbv9PasdZOLv5BPErJqHsU7SsU16RFVAXzGyXL0ALxz30rTDmnyHiTWc6TfNcg+vWZJHQ9A=
  - secure: kxaZ+a8e1ZP/mO5x2P/2lFRZR9qjxhaXdTHjPPd4O6IsOg2Nb4iyPYp8hZWitGsheVuI0QrGeAhskO9Q3W3xqSMtilb7z8xze3tNfQpEVb4Y4kkZrvd27r740Hj9bv/ey4GVjJFQK9jcQ1W0SRR6pFUygJMOwexqEVAeH8E9VZA=
sudo: false

notifications:
  irc: "chat.freenode.net#shapeless"
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/e58e987de2f64f32c8c6
